CONFIG_ZMK_KEYBOARD_NAME="cornesque36-bt"
# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y
# Uncomment the following line to enable deep sleep
# CONFIG_ZMK_SLEEP=y

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
